In [18]:
import numpy as np

In [19]:
tok_virat = np.array([2.2,2.6,3.1])
tok_crickt = np.array([1.1,1.2,1.3])
tok_england = np.array([1.6,2.1,0.234])

print("Token: Virat, Embedding :",tok_virat)
print("Token: Cricket, Embedding :",tok_crickt)
print("Token: England, Embedding :",tok_england)

Token: Virat, Embedding : [2.2 2.6 3.1]
Token: Cricket, Embedding : [1.1 1.2 1.3]
Token: England, Embedding : [1.6   2.1   0.234]


In [20]:
w_v = np.random.rand(3,3)
w_c = np.random.rand(3,3)
w_e = np.random.rand(3,3)

print("Weights for query transformation:" , w_v)
print("Weights for key transformation:" , w_c)
print("Weights for value transformation:" , w_e)

Weights for query transformation: [[0.69110627 0.70992561 0.83357316]
 [0.47315228 0.93144181 0.03186034]
 [0.18583097 0.95253952 0.14057417]]
Weights for key transformation: [[0.68220537 0.75831566 0.33953483]
 [0.98549096 0.70534122 0.0875353 ]
 [0.3365128  0.02732681 0.10018593]]
Weights for value transformation: [[0.33448906 0.21532255 0.12927451]
 [0.13128863 0.53416311 0.30061347]
 [0.61004817 0.50375565 0.73968931]]


In [21]:
query_cric = np.dot(tok_crickt,w_v)

key_virat = np.dot(tok_virat,w_c)
value_virat = np.dot(tok_virat,w_e)

key_eng = np.dot(tok_england,w_c)
value_eng = np.dot(tok_england,w_e)


print("Query, key and value for cricket : ")
print("Query for cricket",query_cric)
print("Key for Virat",key_virat)
print("Value for Virat",value_virat)
print("Key for Engalnd",key_eng)
print("Value for England",key_eng)

Query, key and value for cricket : 
Query for cricket [1.5695799  3.13694971 1.1379093 ]
Key for Virat [5.10631799 3.58689475 1.2851448 ]
Value for Virat [2.96837571 3.42417621 3.35903578]
Key for Engalnd [3.2398036  2.7009161  0.75052338]
Value for England [3.2398036  2.7009161  0.75052338]


In [22]:
simi_cric_virat = np.dot(query_cric,key_virat)
simi_cric_england = np.dot(query_cric,key_eng)

print(simi_cric_virat)
print(simi_cric_england)

20.72906075282525
14.411796123335792
